language: go

# Need to be root because of docker and setuid
sudo: true

env:
    - TRAVIS_NODE_VERSION="stable"

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
            - google-chrome-beta

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install -g angular-cli
    - npm install -g karma
    - npm install

before_script:
    - ng build

script:
    # Make all scripts
    - cd scripts
    - make
    - cd ..
    # Test frontend
    - cd frontend
    - karma start karma.conf.js --single-run
    - cd ..
