version: "2"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "8080:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - DEFAULT_HOST=www.*

    postgres:
        image: postgres
        container_name: postgres
        expose:
            - "5432"

    kro:
        image: docker:dind
        container_name: kro
        depends_on:
            - postgres
        volumes:
            - ./build:/kro/:rw
            - /var/run/docker.sock:/tmp/docker.sock:ro
        expose:
            - "8080"
        command: /kro/kro
        environment:
            - VIRTUAL_HOST=api.*
        links:
            - postgres

    frontend:
        image: nginx
        container_name: frontend
        ports:
            - "4200:80"
        volumes:
            - ./frontend/dist:/usr/share/nginx/html:ro
            - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            - HOST=0.0.0.0
            - VIRTUAL_HOST=www.*
